apiVersion: v1
kind: Service
metadata:
  name: spring-service-application
  namespace: devops
spec:
  selector:
    app: application-service
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
      nodePort: 32095
  type: NodePort