version: "3.9"

services:
  # --- ADS SERVICE EXTENSIONS ---
  ads-service:
    environment:
      SPRING_AI_OLLAMA_BASE_URL: http://dev-ollama:11434

  # --- MANAGEMENT ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-ads-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fawzi-admin@pidev4sae4.com
      PGADMIN_DEFAULT_PASSWORD: fawzi
    ports:
      - "5050:80"
    depends_on:
      - ads-db
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: dev-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - microservices-net

  # --- AI MODELS ---
  ollama:
    image: ollama/ollama:latest
    container_name: dev-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      OLLAMA_KEEP_ALIVE: 24h
    networks:
      - microservices-net

  # --- ANALYTICS ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: dev-clickhouse
    depends_on:
      - kafka
    ports:
      - "8123:8123"
      - "9005:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./ads-service/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./ads-service/clickhouse/users.xml:/etc/clickhouse-server/users.d/default-user.xml
    environment:
      CLICKHOUSE_DB: ads_analytics
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - microservices-net

  grafana:
    build: 
      context: ./ads-service/grafana
    container_name: dev-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ads-service/grafana/provisioning:/etc/grafana/provisioning
      - ./ads-service/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - clickhouse
    networks:
      - microservices-net

  # --- CODE QUALITY ---
  sonarqube:
    image: sonarqube:community
    container_name: dev-sonarqube
    depends_on:
      - sonar-db
    ports:
      - "9001:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - microservices-net

  sonar-db:
    image: postgres:15-alpine
    container_name: dev-sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5433:5432"
    volumes:
      - sonar_data:/var/lib/postgresql/data
    networks:
      - microservices-net

volumes:
  ollama_storage:
  clickhouse_data:
  sonar_data:
  grafana_data:

networks:
  microservices-net:
    external: true

  
