apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ads-pvc
  namespace: prolance
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ads
  namespace: prolance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ads
  template:
    metadata:
      labels:
        app: postgres-ads
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "ads_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-ads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ads
  namespace: prolance
spec:
  selector:
    app: postgres-ads
  ports:
    - port: 5432
      targetPort: 5432
