apiVersion: v1
kind: Secret
metadata:
  name: ads-service-secret
  namespace: prolance
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "super-secret-key-that-is-at-least-32-chars!"
  GROQ_API_KEY: ""
