apiVersion: v1
kind: Service
metadata:
  name: ads-service
  namespace: prolance
  labels:
    app: ads-service
spec:
  type: NodePort
  selector:
    app: ads-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30090
