apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-ads
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: default
      defaultDatabase: ads_analytics
    secureJsonData:
      password: ""
    editable: true
