apiVersion: v1
kind: Service
metadata:
  name: spring-service-project
  namespace: devops
spec:
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
      nodePort: 32094
  type: NodePort