apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: farahchbeb/subscription-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service-subscription:3306/pidev_subscription?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-subscription
                  key: mysql-root-password
            - name: SERVER_PORT
              value: "8090"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service-subscription
  namespace: devops
spec:
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 32090
  type: NodePort
