{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ads-pv
  labels:
    app: postgres-ads
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.size }}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  hostPath:
    path: {{ .Values.postgres.persistence.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ads-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ads
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ads
  template:
    metadata:
      labels:
        app: postgres-ads
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-ads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ads
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres-ads
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
