apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-service
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-service
  template:
    metadata:
      labels:
        app: skill-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: skill-service
          image: yesmine111/skill-service:latest
          ports:
            - containerPort: 8096
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service-skill:3306/pidev_skill?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-skill
                  key: mysql-root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: SERVER_PORT
              value: "8096"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            initialDelaySeconds: 45
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 20