apiVersion: v1
kind: Service
metadata:
  name: spring-service-skill
  namespace: devops
spec:
  selector:
    app: skill-service
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 32096
  type: NodePort