apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: marahmarah123/event-service:IMAGE_TAG
          ports:
            - containerPort: 8085
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://event-mysql.devops.svc.cluster.local:3306/pidev_events?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-mysql-secret
                  key: mysql-root-password