apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: devops
spec:
  selector:
    app: event-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  type: NodePort