apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-commentaire
  namespace: devops
type: Opaque
data:
  mysql-root-password: cm9vdA==               # "root" encodé en base64
  mysql-database: cGlkZXZfY29tbWVudGFpcmU=   # "pidev_commentaire" encodé en base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-commentaire
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-commentaire
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-commentaire
  template:
    metadata:
      labels:
        app: mysql-commentaire
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-commentaire
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-commentaire
                  key: mysql-database
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc-commentaire
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-commentaire
  namespace: devops
spec:
  selector:
    app: mysql-commentaire
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
