apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentaire-service
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentaire-service
  template:
    metadata:
      labels:
        app: commentaire-service
    spec:
      containers:
        - name: commentaire-service
          image: farahchbeb/commentaire-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service-commentaire:3306/pidev_commentaire?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-commentaire
                  key: mysql-root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: SERVER_PORT
              value: "8083"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: commentaire-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 32083
  type: NodePort
